### ISSUE TITLE
No GPU

### ISSUE THREAD

**Issue by mmwebster** [devendrachaplot/DeepRL-Grounding#12]
Any reason why cuda/gpus aren't used here?

**Comment by devendrachaplot** [comment]
Hi,
This codebase uses the A3C algorithm for reinforcement learning, which requires a separate copy of the model for each thread, and thus, typically uses only CPUs. You can check the A3C paper for more details:
https://arxiv.org/pdf/1602.01783.pdf

**Comment by mmwebster** [comment]
Ah I see. Thank you!
