### ISSUE TITLE
Hardware specifications

### ISSUE THREAD

**Issue by a7b23** [devendrachaplot/DeepRL-Grounding#4]
I have been running the code on 32 threads since 3 days but still haven't been able to get avg Accuracy of more than 0.5 for the 'easy' difficulty. Can you specify the hardware that was used for getting the result mentioned in the paper?

**Comment by devendrachaplot** [comment]
The experiments in the paper were run on a DGX-1 with two Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz CPUs. It takes about 35K iterations per thread with 32 threads to reach about 0.5 accuracy on 'easy' environment. What is the number of iterations for you on each thread after 3 days?

**Comment by a7b23** [comment]
It had reached only 15k steps and that is why I guess the performance is low. Thanks for specifying the specifications, will try on a high end machine.

**Comment by rshivansh** [comment]
@devendrachaplot I have been training it on easy difficulty level its 3 days now and avg accuracy has still not crossed 0.35. My system is 48 core cpu.
