### ISSUE TITLE
How is the accuracy calculated ? Its mentioned that it is averaged over 100 episodes, but averaged over which 100 episodes ? Is it from 1 - 100 ?

### ISSUE THREAD

**Issue by rshivansh** [devendrachaplot/DeepRL-Grounding#5]

**Comment by devendrachaplot** [comment]
I am not sure if I understand your question, but accuracy is averaged over 100 separate test episodes at the end of training.

**Comment by rshivansh** [comment]
what is the accuracy returned by running
 python a3c_main.py --evaluate 1 --load saved/pretrained_model
Sorry for such basic questions ! I am still a beginner.

**Comment by devendrachaplot** [comment]
The accuracy can be anywhere between 0.8 and 1.0 because the episodes are generated randomly.

**Comment by rshivansh** [comment]
Yes this is what i wanted to confirm ! So it means once my model is trained , while testing it I test it over any 100 test episodes and then report the avg value right ?
Thanks

**Comment by devendrachaplot** [comment]
Yes, that's correct.

**Comment by rshivansh** [comment]
Thanks @devendrachaplot

**Comment by rshivansh** [comment]
A silly question, @devendrachaplot it is not an issue, just wanted to know that I am currently training my own model for same work (visual grounding) on your modified environment and I am receiving avg reward as 0 for quite a long time now, so could you let me know if this actually happens at the start of training time.
Thanks

**Comment by devendrachaplot** [comment]
The average reward shouldn't be 0. If it's not an issue with the code, you can email me with your questions, attaching the log file and the command you used to run the code.

**Comment by rshivansh** [comment]
@devendrachaplot I have mailed you at  chaplot@cs.cmu.edu. Your help will mean a lot.
Thanks!
