### ISSUE TITLE
How long to train to reproduce the paper results?

### ISSUE THREAD

**Issue by Singularity42** [devendrachaplot/DeepRL-Grounding#6]
Hi

I am experimenting with the code but I don't know how long to let the code run to get the results mentioned in the paper? Can you please let me know that?

Thanks

**Comment by devendrachaplot** [comment]
This depends on your CPU speed. The x-axis of the plots in the paper show the time taken on a DGX-1 with two Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz CPUs.
